using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.IO;
using System.Threading.Tasks;

namespace ToDoOperations
{
    public static class DocCreateToDoItem
    {
        [FunctionName("DocCreateToDoItem")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "items")]HttpRequest req,
            [CosmosDB(
        databaseName: "ToDoItems",
        containerName: "Items",
        Connection = "CosmosDBConnection")]
    IAsyncCollector<object> todos,
            ILogger log)
        {
            log.LogInformation("Creating a new todo list item");
            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            var input = JsonConvert.DeserializeObject<CreateToDoItem>(requestBody);

            var todo = new ToDoItem() { Description = input.Description };
            //the object we need to add has to have a lower case id property or we'll
            // end up with a cosmosdb document with two properties - id (autogenerated) and Id
            await todos.AddAsync(new ToDoItem { Id = todo.Id, CreatedOn = todo.CreatedOn, IsCompleted = todo.IsCompleted, Description = todo.Description });
            return new OkObjectResult(todo);
        }
    }
}
